# fly.toml app configuration file generated for solace-health-takehome on 2023-07-02T17:54:13-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solace-health-takehome"
primary_region = "den"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
